"""
PolicyLang IR -> eBPF C source generator.

v0.1 scope:
- IPv4 only
- TCP / UDP / ICMP
- source.ip
- destination.ip
- source.port
- destination.port
- protocol
- == / !=
- AND / OR
- allow / deny
"""

from __future__ import annotations

from compiler.ir.ir import IRComparison, IRLogical, IRPolicy, IRCondition


class EBPFGenerationError(Exception):
    """Raised when Policy IR cannot be converted to eBPF C."""


FIELD_TO_C = {
    "SRC_IP": "src_ip",
    "DST_IP": "dst_ip",
    "SRC_PORT": "src_port",
    "DST_PORT": "dst_port",
    "PROTOCOL": "protocol",
}


def ipv4_to_u32(ip: str) -> str:
    """Convert dotted IPv4 address into a hexadecimal IPv4 value."""

    parts = ip.split(".")

    if len(parts) != 4:
        raise EBPFGenerationError(f"Invalid IPv4 address: {ip}")

    try:
        octets = [int(part) for part in parts]
    except ValueError:
        raise EBPFGenerationError(f"Invalid IPv4 address: {ip}")

    if any(octet < 0 or octet > 255 for octet in octets):
        raise EBPFGenerationError(f"Invalid IPv4 address: {ip}")

    value = (
        (octets[0] << 24)
        | (octets[1] << 16)
        | (octets[2] << 8)
        | octets[3]
    )

    return f"0x{value:08x}"


def value_to_c(condition: IRComparison) -> str:
    """Convert an IR comparison value into a C expression."""

    if condition.field in {"SRC_IP", "DST_IP"}:
        return ipv4_to_u32(str(condition.value))

    if condition.field in {"SRC_PORT", "DST_PORT"}:
        try:
            return str(int(condition.value))
        except (TypeError, ValueError):
            raise EBPFGenerationError(
                f"Invalid port value: {condition.value}"
            )

    if condition.field == "PROTOCOL":
        protocol = str(condition.value).lower()

        protocol_map = {
            "tcp": "IPPROTO_TCP",
            "udp": "IPPROTO_UDP",
            "icmp": "IPPROTO_ICMP",
        }

        if protocol not in protocol_map:
            raise EBPFGenerationError(
                f"Unsupported protocol: {condition.value}"
            )

        return protocol_map[protocol]

    raise EBPFGenerationError(
        f"Unsupported IR field: {condition.field}"
    )


def comparison_to_c(condition: IRComparison) -> str:
    """Generate a C expression for one comparison."""

    field = FIELD_TO_C.get(condition.field)

    if field is None:
        raise EBPFGenerationError(
            f"Unsupported IR field: {condition.field}"
        )

    operator_map = {
        "EQ": "==",
        "NE": "!=",
    }

    operator = operator_map.get(condition.operator)

    if operator is None:
        raise EBPFGenerationError(
            f"Unsupported IR operator: {condition.operator}"
        )

    value = value_to_c(condition)

    return f"{field} {operator} {value}"


def condition_to_c(condition: IRCondition) -> str:
    """Recursively convert IR conditions into C expressions."""

    if isinstance(condition, IRComparison):
        return comparison_to_c(condition)

    if isinstance(condition, IRLogical):
        operator_map = {
            "AND": "&&",
            "OR": "||",
        }

        operator = operator_map.get(condition.operator)

        if operator is None:
            raise EBPFGenerationError(
                f"Unsupported logical operator: {condition.operator}"
            )

        left = condition_to_c(condition.left)
        right = condition_to_c(condition.right)

        return f"({left} {operator} {right})"

    raise EBPFGenerationError(
        f"Unsupported IR condition: {type(condition).__name__}"
    )


def generate_ebpf_c(policy: IRPolicy) -> str:
    """
    Generate a complete eBPF C program from PolicyLang IR.

    The generated program is designed for TC/classifier-style
    packet filtering.
    """

    condition = condition_to_c(policy.condition)

    # Determine what happens when the policy condition matches
    # and what happens when it does not match.
    if policy.action == "ALLOW":
        match_action = "TC_ACT_OK"
        fallback_action = "TC_ACT_SHOT"

    elif policy.action == "DENY":
        match_action = "TC_ACT_SHOT"
        fallback_action = "TC_ACT_OK"

    else:
        raise EBPFGenerationError(
            f"Unsupported policy action: {policy.action}"
        )

    return f'''/*
 * Generated by PolicyLang compiler.
 *
 * Policy:
 *   action    = {policy.action}
 *   direction = {policy.direction}
 *
 * DO NOT EDIT THIS FILE MANUALLY.
 */

#include <linux/bpf.h>
#include <linux/pkt_cls.h>
#include <linux/if_ether.h>
#include <linux/ip.h>
#include <linux/tcp.h>
#include <linux/udp.h>
#include <linux/in.h>
#include <bpf/bpf_helpers.h>
#include <bpf/bpf_endian.h>

char LICENSE[] SEC("license") = "GPL";

SEC("classifier")
int policylang_filter(struct __sk_buff *skb)
{{
    void *data = (void *)(long)skb->data;
    void *data_end = (void *)(long)skb->data_end;

    struct ethhdr *eth = data;

    if ((void *)(eth + 1) > data_end)
        return TC_ACT_OK;

    if (eth->h_proto != bpf_htons(ETH_P_IP))
        return TC_ACT_OK;

    struct iphdr *ip = (void *)(eth + 1);

    if ((void *)(ip + 1) > data_end)
        return TC_ACT_OK;

    __u32 src_ip = ip->saddr;
    __u32 dst_ip = ip->daddr;

    __u16 src_port = 0;
    __u16 dst_port = 0;
    __u8 protocol = ip->protocol;

    if (protocol == IPPROTO_TCP) {{
        struct tcphdr *tcp = (void *)ip + (ip->ihl * 4);

        if ((void *)(tcp + 1) > data_end)
            return TC_ACT_OK;

        src_port = bpf_ntohs(tcp->source);
        dst_port = bpf_ntohs(tcp->dest);

    }} else if (protocol == IPPROTO_UDP) {{
        struct udphdr *udp = (void *)ip + (ip->ihl * 4);

        if ((void *)(udp + 1) > data_end)
            return TC_ACT_OK;

        src_port = bpf_ntohs(udp->source);
        dst_port = bpf_ntohs(udp->dest);
    }}

    if ({condition})
        return {match_action};

    return {fallback_action};
}}
'''